### ISSUE TITLE
[Question] replay-normalized in tardis-machine based on the localTimestamp

### ISSUE THREAD

**Issue by thangng48** [tardis-dev/tardis-machine#11]
I've read through your docs but don't see anywhere that confirms it.
So, just to ask `from and to` in [replayed-normalized in tardis-machine](https://docs.tardis.dev/api/tardis-machine#http-get-replay-normalized-options-options) are compared against the message's `localTimestamp`, am I right ?

**Comment by thangng48** [comment]
@thaaddeus 

Is there anyway to request data based on exchange's timestamp ?
If not, do you have any plan to implement it ?

**Comment by thaaddeus** [comment]
There's no way to do this, some exchanges do not even provide timestamps for their messages.

**Comment by thangng48** [comment]
> There's no way to do this, some exchanges do not even provide timestamps for their messages.

But the https://docs.tardis.dev/api/tardis-machine#http-get-replay-normalized-options-options actually requests saved data from your data central. It means messages must have timestamp anyway, right ?

**Comment by thaaddeus** [comment]
and that timestamp is a local timestamp (timestamp when message was received by data collection service)
