### ISSUE TITLE
Minimum timestamp difference for replaying websockets

### ISSUE THREAD

**Issue by r614** [tardis-dev/tardis-machine#12]
Hi, 

I am writing some tests using Tardis Machine for replaying normalized data through the websocket endpoint, and I was wondering if there's a minimum difference needed between the `from` and `to` datetime objects to actually replay data, or this is a bug.

I am able to replay data successfully for a time difference of >=1 min, but anything less than that returns no data from the websocket. Ex, if I try replaying data between ["2022-01-01 00:01:00", "2022-01-01 00:02:00"] I successfully receive data, but if I try ["2022-01-01 00:01:00", "2022-01-01 00:01:30"] I get an empty response with no other changes to the code. I know there are messages during that time difference because I receive them with the former arguments. 

I am listening to ~13 exchanges and ~30 symbols, for reference.

**Comment by thaaddeus** [comment]
Hi, yes one minute is minimum resolution.
