### ISSUE TITLE
inconsistent response with okex* exchanges 

### ISSUE THREAD

**Issue by thangng48** [tardis-dev/tardis-machine#13]
We have noticed inconsistency in data response from `tardis-machine`

---
With 2 different tardis-machine instance, with same query `{ symbols: [ 'RVN-USDT-SWAP' ], exchange: 'okex-swap', dataTypes: [ 'trade' ], from: '2022-03-09T05:57:44Z', to: '2022-03-09T06:17:46Z' }`:

- One returns data

```log
tardis-dev:machine GET /replay-normalized request started, options: { symbols: [ 'RVN-USDT-SWAP' ], exchange: 'okex-swap', dataTypes: [ 'trade' ], from: '2022-03-09T05:57:44Z', to: '2022-03-09T06:17:46Z' } +1h
tardis-dev:machine GET /replay-normalized request finished, options: { symbols: [ 'RVN-USDT-SWAP' ], exchange: 'okex-swap', dataTypes: [ 'trade' ], from: '2022-03-09T05:57:44Z', to: '2022-03-09T06:17:46Z' }, time: 8.742 seconds, total messages count: 438 +9s
```

- Other returns nothing

```log
2022-03-09T10:31:38.860Z tardis-dev:machine GET /replay-normalized request started, options: { symbols: [ 'RVN-USDT-SWAP' ], exchange: 'okex-swap', dataTypes: [ 'trade' ], from: '2022-03-09T05:57:44Z', to: '2022-03-09T06:17:46Z' }
2022-03-09T10:31:48.970Z tardis-dev:machine GET /replay-normalized request finished, options: { symbols: [ 'RVN-USDT-SWAP' ], exchange: 'okex-swap', dataTypes: [ 'trade' ], from: '2022-03-09T05:57:44Z', to: '2022-03-09T06:17:46Z' }, time: 10.11 seconds, total messages count: 0
```

---
With same tardis-machine instance

1. inconsistent **replay** data

- `curl -g 'localhost:8000/replay?options={"exchange":"okex","filters":[{"channel":"spot/trade","symbols":["BTC-USDT"]}],"from":"2021-12-23","to":"2021-12-24"}'` returns nothing
- `curl -g 'localhost:8000/replay?options={"exchange":"okex","filters":[{"channel":"spot/trade","symbols":["BTC-USDT"]}],"from":"2021-12-22","to":"2021-12-24"}'` returns data

2. inconsistent **replay** and **replay-normalized** data

- `curl -g 'localhost:8000/replay?options={"exchange":"okex-swap","filters":[{"channel":"swap/trade","symbols":["RVN-USDT-SWAP"]}],"from":"2022-03-09T05:57:44Z","to":"2022-03-09T06:17:46Z"}'` returns nothing
- `curl -g 'localhost:8000/replay-normalized?options={"exchange":"okex-swap","symbols":["RVN-USDT-SWAP"],"from":"2022-03-09T05:57:44Z","to":"2022-03-09T06:17:46Z","dataTypes":["trade"]}'` returns data

**Comment by thaaddeus** [comment]
Can you please update to last tardis-machine version and try again?

We've migrated to okex v5 API (v3 api is discontinued) starting from 2021-12-23 and that means data format and channel names have changed. 

In your case, starting from 2021-12-23 you need to use new channel names for 'replay':
- "trades"
"books-l2-tbt"
"tickers"
"open-interest"
"mark-price"
"price-limit"
"funding-rate"
"status"
"instruments"
"index-tickers"
"liquidations"

Replay-normalized should work fine with latest version
It's not documented yet, but should be soon.

**Comment by thangng48** [comment]
@thaaddeus 

You're correct. 
Just to clarify, the 1st problem happened because one of the tardis-machine instance was in old version.
Thanks you.
