### ISSUE TITLE
Create a parameter for number of workers in cluster mode

### ISSUE THREAD

**Issue by gusostow** [tardis-dev/tardis-machine#18]

**Comment by zbanga** [comment]
if (cluster.isMaster) {
      for (let i = 0; i < numCPUs; i++) {
        cluster.fork()
      }
      
      The number of workers in your cluster is bound by the amount of CPU your server/computer has. It's probably not wise to go beyond the CPU limit as I imagine its probably one thread per CPU.

**Comment by gusostow** [comment]
My desire was to use fewer than my total CPUs

**Comment by zbanga** [comment]
You can edit the file to use less than the total amount if CPUs and pass it in as a parameter.
