### ISSUE TITLE
Create a parameter to disable caching on disk

### ISSUE THREAD

**Issue by gusostow** [tardis-dev/tardis-machine#19]

**Comment by tadeuszwojcik** [comment]
You can try using 'autoCleanup' flag (needs to be added to options payload) - it's not documented yet, but will effectively disable cache.

**Comment by thaaddeus** [comment]
Yes, it also respects autoCleanup (not documented yet)

**Comment by gusostow** [comment]
What's the behavior I should expect from this parameter? I'm still seeing cache files getting saved.

**Comment by thaaddeus** [comment]
there should be only a few files cached and very quickly removed, so there's still some caching internally but very small amount.
