### ISSUE TITLE
Unable to download full history of deribit_volatility_index

### ISSUE THREAD

**Issue by santolex** [tardis-dev/tardis-machine#21]
I have tardis machine(3.20.0) installed in cluster mode in kubernetes.

i'm trying to download full history of deribit_volatiity_index using curl but it stops downloading after some random time.

```sh
curl -v -o - http://tardis.phd.develop/replay?options=%7B%22exchange%22%3A%22deribit%22%2C%22from%22%3A%222021-04-01%22%2C%22to%22%3A%222023-04-13%22%2C%22withDisconnectMessages%22%3Afalse%2C%22filters%22%3A%5B%7B%22symbols%22%3A%5B%22eth_usd%22%5D%2C%22channel%22%3A%22deribit_volatility_index%22%7D%5D%7D > data.json
```

Do you have any clues what i'm doing wrong?

**Comment by zbanga** [comment]
you might be downloading too much at a time.
try chunking down your requests and maybe have an async method to grab the data?
