### ISSUE TITLE
Bybit Instrument Info Broken 

### ISSUE THREAD

**Issue by zbanga** [tardis-dev/tardis-machine#25]
Hi Bybit instrument has been broken since 2023-05-01

https://api.tardis.dev/v1/data-feeds/bybit?from=2023-04-01&filters=[%7B%22channel%22:%22instrument_info%22,%22symbols%22:[%22BTCUSD%22]}]

https://api.tardis.dev/v1/data-feeds/bybit?from=2023-05-01&filters=[%7B%22channel%22:%22instrument_info%22,%22symbols%22:[%22BTCUSD%22]}]

If you hit the endpoints you can see that there is data for one but not the other.

**Comment by thaaddeus** [comment]
Bybit integration was updated to use their V5 API  on 5th of April.
If you use CSV downloads there's nothing you need to do, but if you'd be using tardis-machine it's best to update it to newest version.
If you'd you raw data API new channel names for bybit are:"orderbook.1","orderbook.50","orderbook.500","publicTrade","tickers","liquidation"
Before that it was v2 API (trade channel).
