### ISSUE TITLE
Low price in consolidate data live streaming at 0

### ISSUE THREAD

**Issue by tanguijacob** [tardis-dev/tardis-machine#30]
I got very regularly 0 on LOW price for the binance-futures live streaming, exemple below:

{'type': 'trade_bar', 'symbol': 'BTCUSDT', 'exchange': 'binance-futures', 'name': 'trade_bar_1m', 'interval': 60000, 'kind': 'time', 'open': 63219.4, 'high': 63226, 'low': 0, 'close': 63225.9, 'volume': 46.255000000000216, 'buyVolume': 19.171000000000017, 'sellVolume': 27.083999999999982, 'trades': 834, 'vwap': 63223.22884228705, 'openTimestamp': '2024-09-26T02:38:00.197Z', 'closeTimestamp': '2024-09-26T02:38:59.984Z', 'localTimestamp': '2024-09-26T02:39:00.070Z', 'timestamp': '2024-09-26T02:39:00.000Z', 'local_type': 'trade_bar_1m'}

**Comment by thaaddeus** [comment]
That should be fixed now
