### ISSUE TITLE
Add a commandline option to allow configuration of a proxy server

### ISSUE THREAD

**Issue by rakeshkaria** [tardis-dev/tardis-machine#6]
As per https://github.com/tardis-dev/tardis-node/issues/32, `tardis-node` and `tardis-machine` do not work when run behind a corporate proxy. This issue captures the `tardis-machine` part of the problem.

I propose a `--proxy` argument is added to the `tardismachine.js` binary, such that a proxy can be fed in independently of environment config etc. That argument can then be passed into the `Options` object of `tardis-node`. 

To that end, please see this PR which I think should make this all work: https://github.com/tardis-dev/tardis-machine/pull/5

**Comment by thaaddeus** [comment]
should be working in v3.3.15 via HTTP_PROXY env variable, thanks.
