### ISSUE TITLE
FTX live data

### ISSUE THREAD

**Issue by jzay** [tardis-dev/tardis-machine#7]
Hi, I'm unable to retrieve any live order book data from FTX using this stream option 
```stream_options = [
            {
                "exchange": "ftx",
                "product_ids": ["BTC-PERP"],
                "dataTypes": data_types,
            }

**Comment by thaaddeus** [comment]
I think needs to say 'symbols' not productIds, see https://docs.tardis.dev/api/tardis-machine#websocket-ws-stream-normalized-options-options

**Comment by jzay** [comment]
@thaaddeus sorry that is what I had not sure how that got in there
```            stream_options = [
                {
                    "exchange": "ftx",
                    "symbols": ["BTCUSD"],
                    "dataTypes": data_types,
                }

**Comment by thaaddeus** [comment]
You need to use BTC/USD not BTCUSD, or one of the `availableSymbols` from https://api.tardis.dev/exchanges/v1/ftx
