### ISSUE TITLE
official document clarification

### ISSUE THREAD

**Issue by thangng48** [tardis-dev/tardis-machine#9]
As stated in [official document] (https://docs.tardis.dev/api/tardis-machine#normalized-data-types), `tardis-machine` supports 7 normalized types:
 
![image](https://user-images.githubusercontent.com/55900568/147232805-32a9ee77-a0e3-4ef1-a9d9-ec8734f462ee.png)
 
But in the source code, it supports more data types like:
- `liquidation`: https://github.com/tardis-dev/tardis-machine/blob/d4b6e90a95360f639e8ea95d2038e88496f16c47/src/helpers.ts#L46
- `option_summary`: https://github.com/tardis-dev/tardis-machine/blob/d4b6e90a95360f639e8ea95d2038e88496f16c47/src/helpers.ts#L49

And, I'd tried actual request to my `tardis-machine`, it returns normalized data, for instance of `liquidation`:

```bash
exchanges=("bitmex" "binance-futures" "binance-delivery" "bitfinex-derivatives" "deribit" "ftx" "huobi-dm" "huobi-dm-swap" "huobi-dm-linear-swap")
for ex in ${exchanges[@]}; do 
  count=$(curl -g "http://localhost:8000/replay-normalized?options={\"exchange\":\"${ex}\",\"from\":\"2021-11-30\",\"to\":\"2021-12-01\",\"withDisconnectMessages\":false,\"dataTypes\":[\"liquidation\"]}" | wc -l)
  echo "${ex} = ${count}"
done;

bitmex = 144
binance-futures = 40810
binance-delivery = 1709
bitfinex-derivatives = 78
deribit = 266
ftx = 20745
huobi-dm = 34
huobi-dm-swap = 150
huobi-dm-linear-swap = 1287
```

Are there any inconsistent between the actual behavior and documentation, or I misunderstood some points in your docs or source code ? 
Please clarify it. Thanks !

**Comment by thaaddeus** [comment]
Hi, yes docs simply aren't up to date, new data types not documented are `liquidation` (same format as trade), `option_summary` (fields are documented at https://docs.tardis.dev/downloadable-csv-files#options_chain) and `book_ticker` which is like `quote` but using native tickers/quotes/book_ticker channels of exchanges when supported.
Docs update is on the roadmap, should be finished in Q1 2021.

**Comment by thangng48** [comment]
@thaaddeus 

Thank you for  confirming it. Closing this issue.
